### ISSUE TITLE
Flutter desktop support ?

### ISSUE THREAD

**Issue by GitGud31** [inka-pallycon/pallycon-multidrm-flutter-sample#1]
We're building a streaming app (which uses DRM) using Flutter for multiple platforms, I was wondering if this supports Flutter Desktop?

**Comment by daniel-inka** [comment]
Hi,

Sorry for the delayed reply on the issue.

For better technical support, we have a [Helpdesk service](https://pallycon.zendesk.com) as our primary support channel.
We are not managing the Github issues anymore, and will remove the functionality from all of our repositories.

Please create a ticket on the helpdesk instead if you haven't yet.

Thanks,
Daniel
